name: build-binaries

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    MODEL_PROJECT_NAME: ReSGidency.Models
    EXECUTABLE_PROJECT_NAME: ReSGidency.Console

jobs:
    build-binary:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Run codegen
              run: dotnet build ./src/${{env.MODEL_PROJECT_NAME}}/${{env.MODEL_PROJECT_NAME}}.csproj -Target:ConcatDefinitions
            - name: Build binary
              run: dotnet publish
            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}
                  path: |
                      ./build/bin/${{env.EXECUTABLE_PROJECT_NAME}}/release/native/${{env.EXECUTABLE_PROJECT_NAME}}
                      ./build/bin/${{env.EXECUTABLE_PROJECT_NAME}}/release/native/${{env.EXECUTABLE_PROJECT_NAME}}.exe
