on:
  push:
    branches:
      - ci-test
      
jobs:
  run_e2e:
    name: run end to end
    runs-on: ubuntu-latest

    steps:
    - name: download binary exec
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: build-binaries.yml
        workflow_conclusion: success
        name: ubuntu-latest
    - name: Display structure of downloaded files
      run: ls -R -l -a
    - name: make executable
      run: chmod +x ReSGidency.Console
    - name: run
      run: ./ReSGidency.Console run-end2end -k "${{ secrets.OPENAI_API_KEY }}"
    - name: Display structure of downloaded files
      run: ls -R -l -a
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.2
      with:
        # Artifact name
        name: output-json-array
        path: gpt-parsed.json
